defmodule Phone.Countries do
  def build("376" <> _ = number), do: Phone.AD.build(number)
  def build("971" <> _ = number), do: Phone.AE.build(number)
  def build("93" <> _ = number), do: Phone.AF.build(number)
  def build("355" <> _ = number), do: Phone.AL.build(number)
  def build("374" <> _ = number), do: Phone.AM.build(number)
  def build("244" <> _ = number), do: Phone.AO.build(number)
  def build("54" <> _ = number), do: Phone.AR.build(number)
  def build("43" <> _ = number), do: Phone.AT.build(number)
  def build("297" <> _ = number), do: Phone.AW.build(number)
  def build("994" <> _ = number), do: Phone.AZ.build(number)

  def build!("376" <> _ = number), do: Phone.AD.build!(number)
  def build!("971" <> _ = number), do: Phone.AE.build!(number)
  def build!("93" <> _ = number), do: Phone.AF.build!(number)
  def build!("355" <> _ = number), do: Phone.AL.build!(number)
  def build!("374" <> _ = number), do: Phone.AM.build!(number)
  def build!("244" <> _ = number), do: Phone.AO.build!(number)
  def build!("54" <> _ = number), do: Phone.AR.build!(number)
  def build!("43" <> _ = number), do: Phone.AT.build!(number)
  def build!("297" <> _ = number), do: Phone.AW.build!(number)
  def build!("994" <> _ = number), do: Phone.AZ.build!(number)

  def build("387" <> _ = number), do: Phone.BA.build(number)
  def build("880" <> _ = number), do: Phone.BD.build(number)
  def build("32" <> _ = number), do: Phone.BE.build(number)
  def build("359" <> _ = number), do: Phone.BG.build(number)
  def build("973" <> _ = number), do: Phone.BH.build(number)
  def build("257" <> _ = number), do: Phone.BI.build(number)
  def build("229" <> _ = number), do: Phone.BJ.build(number)
  def build("673" <> _ = number), do: Phone.BN.build(number)
  def build("591" <> _ = number), do: Phone.BO.build(number)
  def build("55" <> _ = number), do: Phone.BR.build(number)
  def build("975" <> _ = number), do: Phone.BT.build(number)
  def build("267" <> _ = number), do: Phone.BW.build(number)
  def build("375" <> _ = number), do: Phone.BY.build(number)
  def build("501" <> _ = number), do: Phone.BZ.build(number)

  def build!("387" <> _ = number), do: Phone.BA.build!(number)
  def build!("880" <> _ = number), do: Phone.BD.build!(number)
  def build!("32" <> _ = number), do: Phone.BE.build!(number)
  def build!("359" <> _ = number), do: Phone.BG.build!(number)
  def build!("973" <> _ = number), do: Phone.BH.build!(number)
  def build!("257" <> _ = number), do: Phone.BI.build!(number)
  def build!("229" <> _ = number), do: Phone.BJ.build!(number)
  def build!("673" <> _ = number), do: Phone.BN.build!(number)
  def build!("591" <> _ = number), do: Phone.BO.build!(number)
  def build!("55" <> _ = number), do: Phone.BR.build!(number)
  def build!("975" <> _ = number), do: Phone.BT.build!(number)
  def build!("267" <> _ = number), do: Phone.BW.build!(number)
  def build!("375" <> _ = number), do: Phone.BY.build!(number)
  def build!("501" <> _ = number), do: Phone.BZ.build!(number)

  def build("243" <> _ = number), do: Phone.CD.build(number)
  def build("236" <> _ = number), do: Phone.CF.build(number)
  def build("242" <> _ = number), do: Phone.CG.build(number)
  def build("41" <> _ = number), do: Phone.CH.build(number)
  def build("225" <> _ = number), do: Phone.CI.build(number)
  def build("682" <> _ = number), do: Phone.CK.build(number)
  def build("56" <> _ = number), do: Phone.CL.build(number)
  def build("237" <> _ = number), do: Phone.CM.build(number)
  def build("86" <> _ = number), do: Phone.CN.build(number)
  def build("57" <> _ = number), do: Phone.CO.build(number)
  def build("506" <> _ = number), do: Phone.CR.build(number)
  def build("53" <> _ = number), do: Phone.CU.build(number)
  def build("238" <> _ = number), do: Phone.CV.build(number)
  def build("599" <> _ = number), do: Phone.CW.build(number)
  def build("357" <> _ = number), do: Phone.CY.build(number)
  def build("420" <> _ = number), do: Phone.CZ.build(number)

  def build!("243" <> _ = number), do: Phone.CD.build!(number)
  def build!("236" <> _ = number), do: Phone.CF.build!(number)
  def build!("242" <> _ = number), do: Phone.CG.build!(number)
  def build!("41" <> _ = number), do: Phone.CH.build!(number)
  def build!("225" <> _ = number), do: Phone.CI.build!(number)
  def build!("682" <> _ = number), do: Phone.CK.build!(number)
  def build!("56" <> _ = number), do: Phone.CL.build!(number)
  def build!("237" <> _ = number), do: Phone.CM.build!(number)
  def build!("86" <> _ = number), do: Phone.CN.build!(number)
  def build!("57" <> _ = number), do: Phone.CO.build!(number)
  def build!("506" <> _ = number), do: Phone.CR.build!(number)
  def build!("53" <> _ = number), do: Phone.CU.build!(number)
  def build!("238" <> _ = number), do: Phone.CV.build!(number)
  def build!("599" <> _ = number), do: Phone.CW.build!(number)
  def build!("357" <> _ = number), do: Phone.CY.build!(number)
  def build!("420" <> _ = number), do: Phone.CZ.build!(number)

  def build("49" <> _ = number), do: Phone.DE.build(number)
  def build("253" <> _ = number), do: Phone.DJ.build(number)
  def build("45" <> _ = number), do: Phone.DK.build(number)
  def build("213" <> _ = number), do: Phone.DZ.build(number)

  def build!("49" <> _ = number), do: Phone.DE.build!(number)
  def build!("253" <> _ = number), do: Phone.DJ.build!(number)
  def build!("45" <> _ = number), do: Phone.DK.build!(number)
  def build!("213" <> _ = number), do: Phone.DZ.build!(number)

  def build("593" <> _ = number), do: Phone.EC.build(number)
  def build("372" <> _ = number), do: Phone.EE.build(number)
  def build("20" <> _ = number), do: Phone.EG.build(number)
  def build("291" <> _ = number), do: Phone.ER.build(number)
  def build("34" <> _ = number), do: Phone.ES.build(number)
  def build("251" <> _ = number), do: Phone.ET.build(number)

  def build!("593" <> _ = number), do: Phone.EC.build!(number)
  def build!("372" <> _ = number), do: Phone.EE.build!(number)
  def build!("20" <> _ = number), do: Phone.EG.build!(number)
  def build!("291" <> _ = number), do: Phone.ER.build!(number)
  def build!("34" <> _ = number), do: Phone.ES.build!(number)
  def build!("251" <> _ = number), do: Phone.ET.build!(number)

  def build("358" <> _ = number), do: Phone.FI.build(number)
  def build("679" <> _ = number), do: Phone.FJ.build(number)
  def build("691" <> _ = number), do: Phone.FM.build(number)
  def build("298" <> _ = number), do: Phone.FO.build(number)
  def build("33" <> _ = number), do: Phone.FR.build(number)

  def build!("358" <> _ = number), do: Phone.FI.build!(number)
  def build!("679" <> _ = number), do: Phone.FJ.build!(number)
  def build!("691" <> _ = number), do: Phone.FM.build!(number)
  def build!("298" <> _ = number), do: Phone.FO.build!(number)
  def build!("33" <> _ = number), do: Phone.FR.build!(number)
end
