defmodule Phone.Countries do
  def build("376" <> _ = number), do: Phone.AD.build(number)
  def build("971" <> _ = number), do: Phone.AE.build(number)
  def build("93" <> _ = number), do: Phone.AF.build(number)
  def build("355" <> _ = number), do: Phone.AL.build(number)
  def build("374" <> _ = number), do: Phone.AM.build(number)
  def build("244" <> _ = number), do: Phone.AO.build(number)
  def build("54" <> _ = number), do: Phone.AR.build(number)
  def build("43" <> _ = number), do: Phone.AT.build(number)
  def build("297" <> _ = number), do: Phone.AW.build(number)
  def build("994" <> _ = number), do: Phone.AZ.build(number)

  def build!("376" <> _ = number), do: Phone.AD.build!(number)
  def build!("971" <> _ = number), do: Phone.AE.build!(number)
  def build!("93" <> _ = number), do: Phone.AF.build!(number)
  def build!("355" <> _ = number), do: Phone.AL.build!(number)
  def build!("374" <> _ = number), do: Phone.AM.build!(number)
  def build!("244" <> _ = number), do: Phone.AO.build!(number)
  def build!("54" <> _ = number), do: Phone.AR.build!(number)
  def build!("43" <> _ = number), do: Phone.AT.build!(number)
  def build!("297" <> _ = number), do: Phone.AW.build!(number)
  def build!("994" <> _ = number), do: Phone.AZ.build!(number)

  def build("387" <> _ = number), do: Phone.BA.build(number)
  def build("880" <> _ = number), do: Phone.BD.build(number)
  def build("32" <> _ = number), do: Phone.BE.build(number)
  def build("359" <> _ = number), do: Phone.BG.build(number)
  def build("973" <> _ = number), do: Phone.BH.build(number)
  def build("257" <> _ = number), do: Phone.BI.build(number)
  def build("229" <> _ = number), do: Phone.BJ.build(number)
  def build("673" <> _ = number), do: Phone.BN.build(number)
  def build("591" <> _ = number), do: Phone.BO.build(number)
  def build("55" <> _ = number), do: Phone.BR.build(number)
  def build("975" <> _ = number), do: Phone.BT.build(number)
  def build("267" <> _ = number), do: Phone.BW.build(number)
  def build("375" <> _ = number), do: Phone.BY.build(number)
  def build("501" <> _ = number), do: Phone.BZ.build(number)

  def build!("387" <> _ = number), do: Phone.BA.build!(number)
  def build!("880" <> _ = number), do: Phone.BD.build!(number)
  def build!("32" <> _ = number), do: Phone.BE.build!(number)
  def build!("359" <> _ = number), do: Phone.BG.build!(number)
  def build!("973" <> _ = number), do: Phone.BH.build!(number)
  def build!("257" <> _ = number), do: Phone.BI.build!(number)
  def build!("229" <> _ = number), do: Phone.BJ.build!(number)
  def build!("673" <> _ = number), do: Phone.BN.build!(number)
  def build!("591" <> _ = number), do: Phone.BO.build!(number)
  def build!("55" <> _ = number), do: Phone.BR.build!(number)
  def build!("975" <> _ = number), do: Phone.BT.build!(number)
  def build!("267" <> _ = number), do: Phone.BW.build!(number)
  def build!("375" <> _ = number), do: Phone.BY.build!(number)
  def build!("501" <> _ = number), do: Phone.BZ.build!(number)

  def build("243" <> _ = number), do: Phone.CD.build(number)
  def build("236" <> _ = number), do: Phone.CF.build(number)
  def build("242" <> _ = number), do: Phone.CG.build(number)
  def build("41" <> _ = number), do: Phone.CH.build(number)
  def build("225" <> _ = number), do: Phone.CI.build(number)
  def build("682" <> _ = number), do: Phone.CK.build(number)
  def build("56" <> _ = number), do: Phone.CL.build(number)
  def build("237" <> _ = number), do: Phone.CM.build(number)
  def build("86" <> _ = number), do: Phone.CN.build(number)
  def build("57" <> _ = number), do: Phone.CO.build(number)
  def build("506" <> _ = number), do: Phone.CR.build(number)
  def build("53" <> _ = number), do: Phone.CU.build(number)
  def build("238" <> _ = number), do: Phone.CV.build(number)
  def build("599" <> _ = number), do: Phone.CW.build(number)
  def build("357" <> _ = number), do: Phone.CY.build(number)
  def build("420" <> _ = number), do: Phone.CZ.build(number)

  def build!("243" <> _ = number), do: Phone.CD.build!(number)
  def build!("236" <> _ = number), do: Phone.CF.build!(number)
  def build!("242" <> _ = number), do: Phone.CG.build!(number)
  def build!("41" <> _ = number), do: Phone.CH.build!(number)
  def build!("225" <> _ = number), do: Phone.CI.build!(number)
  def build!("682" <> _ = number), do: Phone.CK.build!(number)
  def build!("56" <> _ = number), do: Phone.CL.build!(number)
  def build!("237" <> _ = number), do: Phone.CM.build!(number)
  def build!("86" <> _ = number), do: Phone.CN.build!(number)
  def build!("57" <> _ = number), do: Phone.CO.build!(number)
  def build!("506" <> _ = number), do: Phone.CR.build!(number)
  def build!("53" <> _ = number), do: Phone.CU.build!(number)
  def build!("238" <> _ = number), do: Phone.CV.build!(number)
  def build!("599" <> _ = number), do: Phone.CW.build!(number)
  def build!("357" <> _ = number), do: Phone.CY.build!(number)
  def build!("420" <> _ = number), do: Phone.CZ.build!(number)

  def build("49" <> _ = number), do: Phone.DE.build(number)
  def build("253" <> _ = number), do: Phone.DJ.build(number)
  def build("45" <> _ = number), do: Phone.DK.build(number)
  def build("213" <> _ = number), do: Phone.DZ.build(number)

  def build!("49" <> _ = number), do: Phone.DE.build!(number)
  def build!("253" <> _ = number), do: Phone.DJ.build!(number)
  def build!("45" <> _ = number), do: Phone.DK.build!(number)
  def build!("213" <> _ = number), do: Phone.DZ.build!(number)

  def build("593" <> _ = number), do: Phone.EC.build(number)
  def build("372" <> _ = number), do: Phone.EE.build(number)
  def build("20" <> _ = number), do: Phone.EG.build(number)
  def build("291" <> _ = number), do: Phone.ER.build(number)
  def build("34" <> _ = number), do: Phone.ES.build(number)
  def build("251" <> _ = number), do: Phone.ET.build(number)

  def build!("593" <> _ = number), do: Phone.EC.build!(number)
  def build!("372" <> _ = number), do: Phone.EE.build!(number)
  def build!("20" <> _ = number), do: Phone.EG.build!(number)
  def build!("291" <> _ = number), do: Phone.ER.build!(number)
  def build!("34" <> _ = number), do: Phone.ES.build!(number)
  def build!("251" <> _ = number), do: Phone.ET.build!(number)

  def build("358" <> _ = number), do: Phone.FI.build(number)
  def build("679" <> _ = number), do: Phone.FJ.build(number)
  def build("691" <> _ = number), do: Phone.FM.build(number)
  def build("298" <> _ = number), do: Phone.FO.build(number)
  def build("33" <> _ = number), do: Phone.FR.build(number)

  def build!("358" <> _ = number), do: Phone.FI.build!(number)
  def build!("679" <> _ = number), do: Phone.FJ.build!(number)
  def build!("691" <> _ = number), do: Phone.FM.build!(number)
  def build!("298" <> _ = number), do: Phone.FO.build!(number)
  def build!("33" <> _ = number), do: Phone.FR.build!(number)

  def build("241" <> _ = number), do: Phone.GA.build(number)
  def build("44" <> _ = number), do: Phone.GB.build(number)
  def build("995" <> _ = number), do: Phone.GE.build(number)
  def build("594" <> _ = number), do: Phone.GF.build(number)
  def build("233" <> _ = number), do: Phone.GH.build(number)
  def build("350" <> _ = number), do: Phone.GI.build(number)
  def build("299" <> _ = number), do: Phone.GL.build(number)
  def build("220" <> _ = number), do: Phone.GM.build(number)
  def build("224" <> _ = number), do: Phone.GN.build(number)
  def build("240" <> _ = number), do: Phone.GQ.build(number)
  def build("30" <> _ = number), do: Phone.GR.build(number)
  def build("502" <> _ = number), do: Phone.GT.build(number)
  def build("245" <> _ = number), do: Phone.GW.build(number)
  def build("592" <> _ = number), do: Phone.GY.build(number)

  def build!("241" <> _ = number), do: Phone.GA.build!(number)
  def build!("44" <> _ = number), do: Phone.GB.build!(number)
  def build!("995" <> _ = number), do: Phone.GE.build!(number)
  def build!("594" <> _ = number), do: Phone.GF.build!(number)
  def build!("233" <> _ = number), do: Phone.GH.build!(number)
  def build!("350" <> _ = number), do: Phone.GI.build!(number)
  def build!("299" <> _ = number), do: Phone.GL.build!(number)
  def build!("220" <> _ = number), do: Phone.GM.build!(number)
  def build!("224" <> _ = number), do: Phone.GN.build!(number)
  def build!("240" <> _ = number), do: Phone.GQ.build!(number)
  def build!("30" <> _ = number), do: Phone.GR.build!(number)
  def build!("502" <> _ = number), do: Phone.GT.build!(number)
  def build!("245" <> _ = number), do: Phone.GW.build!(number)
  def build!("592" <> _ = number), do: Phone.GY.build!(number)

  def build("852" <> _ = number), do: Phone.HK.build(number)
  def build("504" <> _ = number), do: Phone.HN.build(number)
  def build("385" <> _ = number), do: Phone.HR.build(number)
  def build("509" <> _ = number), do: Phone.HT.build(number)
  def build("36" <> _ = number), do: Phone.HU.build(number)

  def build!("852" <> _ = number), do: Phone.HK.build!(number)
  def build!("504" <> _ = number), do: Phone.HN.build!(number)
  def build!("385" <> _ = number), do: Phone.HR.build!(number)
  def build!("509" <> _ = number), do: Phone.HT.build!(number)
  def build!("36" <> _ = number), do: Phone.HU.build!(number)

  def build("62" <> _ = number), do: Phone.ID.build(number)
  def build("353" <> _ = number), do: Phone.IE.build(number)
  def build("972" <> _ = number), do: Phone.IL.build(number)
  def build("91" <> _ = number), do: Phone.IN.build(number)
  def build("246" <> _ = number), do: Phone.IO.build(number)
  def build("964" <> _ = number), do: Phone.IQ.build(number)
  def build("98" <> _ = number), do: Phone.IR.build(number)
  def build("354" <> _ = number), do: Phone.IS.build(number)
  def build("39" <> _ = number), do: Phone.IT.build(number)

  def build!("62" <> _ = number), do: Phone.ID.build!(number)
  def build!("353" <> _ = number), do: Phone.IE.build!(number)
  def build!("972" <> _ = number), do: Phone.IL.build!(number)
  def build!("91" <> _ = number), do: Phone.IN.build!(number)
  def build!("246" <> _ = number), do: Phone.IO.build!(number)
  def build!("964" <> _ = number), do: Phone.IQ.build!(number)
  def build!("98" <> _ = number), do: Phone.IR.build!(number)
  def build!("354" <> _ = number), do: Phone.IS.build!(number)
  def build!("39" <> _ = number), do: Phone.IT.build!(number)

  def build("962" <> _ = number), do: Phone.JO.build(number)
  def build("81" <> _ = number), do: Phone.JP.build(number)

  def build!("962" <> _ = number), do: Phone.JO.build!(number)
  def build!("81" <> _ = number), do: Phone.JP.build!(number)

  def build("254" <> _ = number), do: Phone.KE.build(number)
  def build("996" <> _ = number), do: Phone.KG.build(number)
  def build("855" <> _ = number), do: Phone.KH.build(number)
  def build("686" <> _ = number), do: Phone.KI.build(number)
  def build("269" <> _ = number), do: Phone.KM.build(number)
  def build("850" <> _ = number), do: Phone.KP.build(number)
  def build("82" <> _ = number), do: Phone.KR.build(number)
  def build("965" <> _ = number), do: Phone.KW.build(number)

  def build!("254" <> _ = number), do: Phone.KE.build!(number)
  def build!("996" <> _ = number), do: Phone.KG.build!(number)
  def build!("855" <> _ = number), do: Phone.KH.build!(number)
  def build!("686" <> _ = number), do: Phone.KI.build!(number)
  def build!("269" <> _ = number), do: Phone.KM.build!(number)
  def build!("850" <> _ = number), do: Phone.KP.build!(number)
  def build!("82" <> _ = number), do: Phone.KR.build!(number)
  def build!("965" <> _ = number), do: Phone.KW.build!(number)
end
